### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Caliel666** [Caliel666/wpplinkmaker#1]
- [ ] add different languages and switch based on system language without the need of language files being present in bin directory (currently pt_BR is hard coded)
- [ ] copy to clipboard button with feedback that it has been copied
- [ ] reduce file size (a app this simple has no business being higher than 1 MB)
